### PR TITLE
bump version of mocha to fix crit issue

### PR DESCRIPTION
**Pull request by lordNikon-95**

### CODE REVIEW

**Comment by jordandlaman** [comment]
NPM audit return a critical issue with growl via the version of mocha installed.

**Review by savagrk — APPROVED** [review]
Approved mocha upgrade.

**Comment by lordNikon-95** [comment]
@savagrk would it be possible to publish a new version so this could be consumed via npm package?

**Comment by savagrk** [comment]
npm package is updated.

**Comment by lordNikon-95** [comment]
You are awesome

**Pull request merged**
